version: '3.8'
services:   # déclaration of services
  api:      #first service php with apache server
    build:  #build from dockerfile
      dockerfile: ./api/Dockerfile
    #configuration of server
    ports:
      - 80:80
    volumes:
      - type: bind          #mount/sharing of api 
        source: ./api/app
        target: /var/www/html
      - type: bind          #sharing server configuration
        source: ./api/apache2/apache2.conf
        target: /etc/apache2/apache2.conf
    env_file:   #access to environment sql variables 
      - ./sql/.env
    depends_on: #dependency bdd
      - mysql
  mysql: #second service
    image: mysql  
    #configuration
    ports:
      - 3307:3306
    env_file:     #access to environment sql variables 
      - ./sql/.env
    volumes:
      - type: volume
        source: api_vol
        target: /var/lib/mysql
      - type: bind          #mount/sharing of sql db
        source: ./sql
        target: /home
volumes: #volume creation
  api_vol: